---
 - hosts: all
   ignore_errors: yes
   become: yes
   tasks:

    - name: Install httpd package
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_distribution  == "Ubuntu"